DROP FUNCTION IF EXISTS `REMOVER_CARACTERES_ESPECIAIS`;
DELIMITER //
/* http://stackoverflow.com/a/22903586/1815558 */
create FUNCTION `REMOVER_CARACTERES_ESPECIAIS`(str VARCHAR(1000)) RETURNS VARCHAR(1000)
BEGIN
	DECLARE i, len SMALLINT DEFAULT 1;
	DECLARE ret VARCHAR(1000) DEFAULT '';
	DECLARE c CHAR(1);
	SET len = CHAR_LENGTH( str );
	REPEAT
	BEGIN
		SET c = MID( str, i, 1 );
		IF c REGEXP '[[:alnum:]]' THEN
		SET ret=CONCAT(ret,c);
		END IF;
		SET i = i + 1;
	END;
	UNTIL i > len END REPEAT;
	RETURN ret;
END//
DELIMITER ;
